Add static assertion construction
- assertion will be done during compilation
- {} is required for
```
error: expected expression before '_Static_assert'
```