Remove `syscall` replacement to avoid
/usr/bin/ld: contrib/build/libunwind/src/.libs/libunwind.a(Linit.o): in function `msync_validate':
Linit.c:(.text+0x183): undefined reference to `scopelibc_syscall'
/usr/bin/ld: contrib/build/libunwind/src/.libs/libunwind.a(Linit.o): in function `mincore_validate':
Linit.c:(.text+0x28d): undefined reference to `scopelibc_syscall'