Splunk test Fix bootstrap Python 3.6 build error
In pip install version 22.0 - Python 3.6 support was dropped [1]
Use alternative link including Python version for install pip

Avoid following error:
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.

Ref: [1]https://github.com/pypa/pip/pull/10641